from faker import Faker
import random


faker = Faker()
nationalities = {
    "Afghanistan":"Afghan",
    "Albania":"Albanian",
    "Algeria":"Algerian",
    "Argentina":"Argentinian",
    "Australia":"Australian",
    "Austria":"Austrian",
    "Bangladesh":"Bangladeshi",
    "Belgium":"Belgian",
    "Bolivia":"Bolivian",
    "Botswana":"Botswanan",
    "Brazil":"Brazilian",
    "Bulgaria":"Bulgarian",
    "Cambodia":"Cambodian",
    "Cameroon":"Cameroonian",
    "Canada":"Canadian",
    "Chile":"Chilean",
    "China":"Chinese",
    "Colombia":"Colombian",
    "Costa Rica":"Costa Rican",
    "Croatia":"Croatian",
    "Cuba":"Cuban",
    "Czech Republic":"Czech",
    "Denmark":"Danish",
    "Dominican Republic":"Dominican",
    "Ecuador":"Ecuadorian",
    "Egypt":"Egyptian",
    "El Salvador":"Salvadorian",
    "England":"English",
    "Estonia":"Estonian",
    "Ethiopia":"Ethiopian",
    "Fiji":"Fijian",
    "Finland":"Finnish",
    "France":"French",
    "Germany":"German",
    "Ghana":"Ghanaian",
    "Greece":"Greek",
    "Guatemala":"Guatemalan",
    "Haiti":"Haitian",
    "Honduras":"Honduran",
    "Hungary":"Hungarian",
    "Iceland":"Icelandic",
    "India":"Indian",
    "Indonesia":"Indonesian",
    "Iran":"Iranian",
    "Iraq":"Iraqi",
    "Ireland":"Irish",
    "Israel":"Israeli",
    "Italy":"Italian",
    "Jamaica":"Jamaican",
    "Japan":"Japanese",
    "Jordan":"Jordanian",
    "Kenya":"Kenyan",
    "Kuwait":"Kuwaiti",
    "Laos":"Lao",
    "Latvia":"Latvian",
    "Lebanon":"Lebanese",
    "Libya":"Libyan",
    "Lithuania":"Lithuanian",
    "Madagascar":"Malagasy",
    "Malaysia":"Malaysian",
    "Mali":"Malian",
    "Malta":"Maltese",
    "Mexico":"Mexican",
    "Mongolia":"Mongolian",
    "Morocco":"Moroccan",
    "Mozambique":"Mozambican",
    "Namibia":"Namibian",
    "Nepal":"Nepalese",
    "Netherlands":"Dutch",
    "New ZealandNew":"Zealand",
    "Nicaragua":"Nicaraguan",
    "Nigeria":"Nigerian",
    "Norway":"Norwegian",
    "Pakistan":"Pakistani",
    "Panama":"Panamanian",
    "Paraguay":"Paraguayan",
    "Peru":"Peruvian",
    "Philippines":"Philippine",
    "Poland":"Polish",
    "Portugal":"Portuguese",
    "Romania":"Romanian",
    "Russia":"Russian",
    "Saudi Arabia":"Saudi",
    "Scotland":"Scottish",
    "Senegal":"Senegalese",
    "Serbia":"Serbian",
    "Singapore":"Singaporean",
    "Slovakia":"Slovak",
    "South Africa":"South African",
    "South Korea":"Korean",
    "Spain":"Spanish",
    "Sri Lanka":"Sri Lankan",
    "Sudan":"Sudanese",
    "Sweden":"Swedish",
    "Switzerland":"Swiss",
    "Syria":"Syrian",
    "Taiwan":"Taiwanese",
    "Tajikistan":"Tajikistani",
    "Thailand":"Thai",
    "Tonga":"Tongan",
    "Tunisia":"Tunisian",
    "Turkey":"Turkish",
    "Ukraine":"Ukrainian",
    "United Arab Emirates":"Emirati",
    "United Kingdom":"British",
    "United States":"American",
    "Uruguay":"Uruguayan",
    "Venezuela":"Venezuelan",
    "Vietnam":"Vietnamese",
    "Wales":"Welsh",
    "Zambia":"Zambian",
    "Zimbabwe":"Zimbabwean",
}

counter = 0
with open("books.sql", "w") as f:
    for i in range(1000):
        values = []
        f.write("INSERT INTO books (book_id,title,author_name,genre,country,release_year,author_id, description) VALUES")
        for j in range(1000):
            counter += 1

            authorID = random.randint(1,1000000)
            author_name = faker.first_name() + " " + faker.last_name()
            title = faker.catch_phrase()
            genre = faker.words(1)[0]
            country = random.choice(list(nationalities.keys()))
            releaseYear = faker.year()
            description = faker.text(max_nb_chars=150)
            values.append(f"({counter}, '{title}', '{author_name}', '{genre}', '{country}', '{releaseYear}', '{authorID}', '{description}')")
        f.write(", ".join(values) + ";\n")